### ISSUE TITLE
Error with UnsafeMutableRawPointer when compiling on arm Mac

### ISSUE THREAD

**Issue by novitae** [paradiseduo/appdecrypt#28]
I just bought an M1 Mac air just to decrypt IPA apps. I installed Xcode on it (version 13.0, the latest available for macOS 11.3). When trying to run the `build-macOS_arm.sh` script, I get the following error:
```
/Users/n/appdecrypt/Sources/appdecrypt/dump.swift:191:18: error: value of optional type 'UnsafeMutableRawPointer?' must be unwrapped to a value of type 'UnsafeMutableRawPointer'
            free(base)
                 ^
/Users/n/appdecrypt/Sources/appdecrypt/dump.swift:191:18: note: coalesce using '??' to provide a default when the optional value contains 'nil'
            free(base)
                 ^
                      ?? <#default value#>
/Users/n/appdecrypt/Sources/appdecrypt/dump.swift:191:18: note: force-unwrap using '!' to abort execution if the optional value contains 'nil'
            free(base)
                 ^
                     !
```
How can I fix this ? Thanks !

**Comment by novitae** [comment]
Works on latest version of Xcode (15.1), macOS 14.2.1

**Comment by asdfzxcvbn** [comment]
> Works on latest version of Xcode (15.1), macOS 14.2.1

and it actually decrypts apps successfully on that version? no issues?
